transport_task:
  description: >
    Respon a: {user_message}
    Dona informació clara sobre el sistema de transport intern de l’aeroport: disponibilitat de vehicles,
    temps estimat de desplaçament entre terminals, rutes recomanades i ubicació de les estacions.
  expected_output: >
    Resposta completa i entenedora amb:
      - Rutes disponibles entre punts de l’aeroport
      - Temps estimats de desplaçament
      - Horari i disponibilitat de vehicles
      - Punt d’origen i destinació correctament identificats
  agent: transport_agent
