task_find_service:
  description: >
    Busca en la información del aeropuerto detalles relevantes que respondan a la pregunta: '{user_message}'.
    Teniendo como referencia el documento csv dades_serveis.csv
  expected_output: >
    Servicio o servicios encontrados que coincidan con la necesidad del usuario.
    Si la información solicitada no se encuentra en el archivo, indica educadamente que no se dispone de datos al respecto.
  agent: service_finder

task_generate_response:
  description: >
    Redacta una respuesta clara y amigable basada en la información encontrada por el Buscador de Servicios.
    IMPORTANTE: Genera la respuesta en el idioma del usuario: '{language}'.
  expected_output: >
    Respuesta final en el idioma solicitado.
  agent: response_generator

